

export default [
    {
        "event_series": "Renegade",
        "name": "Renegade - Summer Meltdown",
        "date": "2022-07-23",
        "stats": "Renegade - Summer Meltdown.json",
        "slug": "2022_renegade_summer_meltdown",
        "format": {
            "name": "Modified Standard 350",
            "slug": "modified_standard_350",
            "reputation": 350,
            "funding": 1500,
        },
        "cross_event": true,
        "supplimentary_data": false,
    },
    {
        "event_series": "Renegade",
        "name": "Renegade - Summer Meltdown - Sunday Slam",
        "date": "2022-07-24",
        "stats": "Renegade - Summer Meltdown - Sunday Slam.json",
        "slug": "2022_renegade_summer_meltdown_sunday_slam",
        "format": {
            "name": "Modified Standard 250",
            "slug": "modified_standard_250",
            "reputation": 250,
            "funding": 1500,
        },
        "cross_event": false,
        "supplimentary_data": false,
    },
    {
        "event_series": "Renegade",
        "name": "Renegade - Spring Up GT",
        "date": "2022-04-23",
        "stats": "Renegade - Spring Up GT.json",
        "slug": "2022_renegade_spring_up_gt",
        "format": {
            "name": "Modified Standard 350",
            "slug": "modified_standard_350",
            "reputation": 350,
            "funding": 1500,
        },
        "cross_event": true,
        "supplimentary_data": false,
    },
    {
        "event_series": "The Long Halloween",
        "name": "The Long Halloween",
        "date": "2022-10-29",
        "stats": "Long Halloween 2022.json",
        "slug": "2022_long_halloween",
        "format": {
            "name": "Batmatch 350",
            "slug": "batmatch_350",
            "reputation": 350,
            "funding": 1500,
        },
        "cross_event": true,
        "supplimentary_data": false,
    },
    {
        "event_series": "Renegade",
        "name": "Renedade Open - The Riddlers Renegade Rampage I",
        "date": "2022-11-18",
        "stats": "2022_11_18_Renegade_Open__The_Riddlers_Renegade_Rampage_1.json",
        "slug": "2022_renegade_open_riddles_rampage",
        "format": {
            "name": "Modified Standard 250",
            "slug": "modified_standard_250",
            "reputation": 250,
            "funding": 1000,
        },
        "cross_event": true,
        "supplimentary_data": true,
    },
    {
        "event_series": "Renegade",
        "name": "Renedade Open - Knightfall 5",
        "date": "2022-11-19",
        "stats": "2022_11_19_Renegade_Open__Knightfall_5.json",
        "slug": "2022_renegade_open_knightfall_5",
        "format": {
            "name": "Modified Standard 350",
            "slug": "modified_standard_350",
            "reputation": 350,
            "funding": 1500,
        },
        "cross_event": true,
        "supplimentary_data": true,
    },
    {
        "event_series": "Adepticon",
        "name": "Battle for the Cowl",
        "date": "2023-03-24",
        "stats": "2023_03_24_Battle_for_the_Cowl.json",
        "slug": "2023_battle_for_the_cowl",
        "format": {
            "name": "Modified Standard 350",
            "slug": "modified_standard_350",
            "reputation": 350,
            "funding": 1500,
        },
        "cross_event": true,
        "supplimentary_data": false,
    },
    {
        "event_series": "Adepticon",
        "name": "Streets of Gotham",
        "date": "2023-03-23",
        "stats": "2023_03_23_Streets_of_Gotham.json",
        "slug": "2023_streets_of_gotham",
        "format": {
            "name": "Modified Standard 350",
            "slug": "modified_standard_350",
            "reputation": 350,
            "funding": 1500,
        },
        "cross_event": true,
        "supplimentary_data": false,
    },
]